export const CREATE_LOCATION = "CREATE_LOCATION";
export const RETRIEVE_LOCATIONS = "RETRIEVE_LOCATIONS";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
// export const SET_LOCATION = "SET_LOCATION";